// packages/frontend/src/lib/components/ApiTypeSelector.svelte
<script lang="ts">
  import type { ApiType, NetworkInfo } from '../types'

  type Props = {
    urlType: ApiType
    network: NetworkInfo | null
    onselect: (type: ApiType) => void
    onreset: () => void
    onloadtokens: () => void
    ongenerate: () => void
  }
  const { urlType, network, onselect, onreset, onloadtokens, ongenerate }: Props = $props()
  let t = $state<ApiType>(urlType)
  $effect(() => {
    t = urlType
  })
  const selectType = (type: ApiType) => {
    if (type !== urlType) {
      t = type
      onselect(type)
      onreset()

      if (type === 'token' && network) {
        onloadtokens()
      } else if (type === 'network' && network) {
        ongenerate()
      }
    }
  }
</script>

<div class="space-y-2">
  <div class="grid grid-cols-1 gap-2 md:grid-cols-2">
    <button
      class="btn {urlType === 'token' ? 'variant-filled-primary' : 'variant-ghost'}"
      onclick={() => selectType('token')}>
      <i class="fas fa-coins mr-2"></i>
      Token Icon
    </button>
    <button
      class="btn {urlType === 'network' ? 'variant-filled-primary' : 'variant-ghost'}"
      onclick={() => selectType('network')}>
      <i class="fas fa-network-wired mr-2"></i>
      Network Icon
    </button>
  </div>
</div>

// packages/ui/src/lib/components/ApiTypeSelector.tsx
import type { ApiType, NetworkInfo } from '../types'

interface ApiTypeSelectorProps {
  urlType: ApiType
  network: NetworkInfo | null
  onSelect: (type: ApiType) => void
  onReset: () => void
  onLoadTokens: () => void
  onGenerate: () => void
}

export default function ApiTypeSelector({
  urlType,
  network,
  onSelect,
  onReset,
  onLoadTokens,
  onGenerate,
}: ApiTypeSelectorProps) {
  const selectType = (type: ApiType) => {
    if (type === urlType) return

    onSelect(type)
    onReset()

    if (type === 'token' && network) {
      onLoadTokens()
    } else if (type === 'network' && network) {
      onGenerate()
    }
  }

  return (
    <div className="space-y-2">
      <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
        <button
          type="button"
          className={`btn ${urlType === 'token' ? 'variant-filled-primary' : 'variant-ghost'}`}
          onClick={() => selectType('token')}
        >
          <i className="fas fa-coins mr-2"></i>
          Token Icon
        </button>
        <button
          type="button"
          className={`btn ${urlType === 'network' ? 'variant-filled-primary' : 'variant-ghost'}`}
          onClick={() => selectType('network')}
        >
          <i className="fas fa-network-wired mr-2"></i>
          Network Icon
        </button>
      </div>
    </div>
  )
}
