// packages/ui/src/lib/components/Attribution.tsx
import { attributionProviders } from '../attribution-providers'
import { useTheme } from '../contexts/ThemeContext'

export default function Attribution() {
  const { isDark } = useTheme()

  return (
    <div className="flex flex-col items-center gap-4">
      <p className="text-sm text-surface-600 dark:text-surface-300 text-center italic">
        Powered by
      </p>

      <div className="flex flex-wrap max-w-sm gap-4 items-center justify-center">
        {attributionProviders.map((provider) => (
          <a
            key={provider.name}
            href={provider.link}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center p-0 hover:opacity-75 transition-opacity"
            title={provider.name}
          >
            <img
              src={
                provider.imageUrl.startsWith('http')
                  ? provider.imageUrl
                  : `/logos/${isDark ? 'dark' : 'light'}/${provider.imageUrl}`
              }
              alt={provider.name}
              width={48}
              className="max-h-12 max-w-24 object-contain"
            />
          </a>
        ))}
      </div>
    </div>
  )
}

// packages/ui/src/lib/components/Attribution.svelte
<script lang="ts">
  import { attributionProviders } from '../attribution-providers'
  import { isDark } from '../stores/theme'
</script>

<div class="flex flex-col items-center gap-4">
  <p class="text-sm text-surface-600 dark:text-surface-300 text-center italic">
    Powered by
  </p>

  <div class="flex flex-wrap max-w-sm gap-4 items-center justify-center">
    {#each attributionProviders as provider}
      <a
        href={provider.link}
        target="_blank"
        rel="noopener noreferrer"
        class="flex items-center justify-center p-0 hover:opacity-75 transition-opacity"
        title={provider.name}
      >
        <img
          src={provider.imageUrl.startsWith('http') ? provider.imageUrl : `/logos/${$isDark ? 'dark' : 'light'}/${provider.imageUrl}`}
          alt={provider.name}
          width={48}
          class="max-h-12 max-w-24 object-contain"
        />
      </a>
    {/each}
  </div>
</div>
