// packages/ui/src/lib/components/NetworkSelect.tsx
import { useState, useMemo, Fragment } from 'react'
import { Dialog, DialogPanel, Transition, TransitionChild } from '@headlessui/react'
import { useSettings } from '../contexts/SettingsContext'
import { useMetricsContext } from '../contexts/MetricsContext'
import { getNetworkName } from '../utils/network-name'
import { getApiUrl } from '../utils'
import type { NetworkInfo } from '../types'

interface NetworkSelectProps {
  selectedChainId: string | null
  onSelect: (chainId: string) => void
}

export default function NetworkSelect({ selectedChainId, onSelect }: NetworkSelectProps) {
  const [isOpen, setIsOpen] = useState(false)
  const { showTestnets, setShowTestnets } = useSettings()
  const { metrics } = useMetricsContext()

  const sortedNetworks = useMemo(() => {
    if (!metrics) return []
    return sortNetworks(metrics.networks.supported, showTestnets)
  }, [metrics, showTestnets])

  const selectedNetwork = useMemo(
    () => sortedNetworks.find((n) => n.chainId.toString() === selectedChainId) ?? null,
    [sortedNetworks, selectedChainId],
  )

  return (
    <div className="relative w-full">
      <div className="mb-2 flex items-center justify-end">
        <TestnetToggle showTestnets={showTestnets} setShowTestnets={setShowTestnets} />
      </div>

      <button
        type="button"
        className="flex w-full items-center justify-between rounded-xl border border-border-dark bg-surface-1 px-4 py-2.5 text-left text-sm transition-colors hover:border-accent-500/40"
        onClick={() => setIsOpen(true)}
      >
        {selectedNetwork ? (
          <span className="flex items-center gap-2 truncate">
            <img
              src={getApiUrl(`/image/${selectedNetwork.chainId}`)}
              alt=""
              width={20}
              height={20}
              className="inline-block rounded-full"
              onError={(e) => {
                ;(e.target as HTMLImageElement).style.display = 'none'
              }}
            />
            {getNetworkName(selectedNetwork.chainId)}{' '}
            <span className="text-white/40">(Chain ID: {selectedNetwork.chainId})</span>
          </span>
        ) : (
          <span className="text-white/40">Choose a network...</span>
        )}
        <i
          className={`fas fa-chevron-down flex-shrink-0 text-accent-500/60 transition-transform ${isOpen ? 'rotate-180' : ''}`}
        />
      </button>

      <NetworkDialog
        isOpen={isOpen}
        onClose={() => setIsOpen(false)}
        sortedNetworks={sortedNetworks}
        selectedChainId={selectedChainId}
        onPick={(network) => {
          setIsOpen(false)
          onSelect(network.chainId.toString())
        }}
      />
    </div>
  )
}

/* -------------------------------------------------------------------------- */
/*  Shared helpers                                                            */
/* -------------------------------------------------------------------------- */

function sortNetworks(networks: NetworkInfo[], showTestnets: boolean): NetworkInfo[] {
  const priorityChains = ['1', '369']

  let filtered = networks
  if (!showTestnets) {
    filtered = networks.filter(
      (network) => !getNetworkName(network.chainId).toLowerCase().includes('testnet'),
    )
  }

  return [...filtered].sort((a, b) => {
    const aId = a.chainId.toString()
    const bId = b.chainId.toString()
    const aIdx = priorityChains.indexOf(aId)
    const bIdx = priorityChains.indexOf(bId)

    if (aIdx !== -1 && bIdx === -1) return -1
    if (aIdx === -1 && bIdx !== -1) return 1
    if (aIdx !== -1 && bIdx !== -1) return aIdx - bIdx

    return getNetworkName(a.chainId).localeCompare(getNetworkName(b.chainId))
  })
}

function TestnetToggle({
  showTestnets,
  setShowTestnets,
}: {
  showTestnets: boolean
  setShowTestnets: (v: boolean) => void
}) {
  return (
    <label className="group flex cursor-pointer items-center gap-3">
      <div className="relative flex">
        <input
          type="checkbox"
          className="peer sr-only"
          checked={showTestnets}
          onChange={(e) => setShowTestnets(e.target.checked)}
        />
        <div className="h-6 w-11 rounded-full bg-surface-3 transition-colors peer-checked:bg-accent-500/20" />
        <div className="absolute left-1 top-1 h-4 w-4 rounded-full bg-white/60 transition-all peer-checked:translate-x-5 peer-checked:bg-accent-500" />
      </div>
      <span className="text-sm font-medium text-white/50 transition-colors group-hover:text-accent-500">
        Show&nbsp;Testnets
      </span>
    </label>
  )
}

function NetworkDialog({
  isOpen,
  onClose,
  sortedNetworks,
  selectedChainId,
  onPick,
}: {
  isOpen: boolean
  onClose: () => void
  sortedNetworks: NetworkInfo[]
  selectedChainId: string | null
  onPick: (network: NetworkInfo) => void
}) {
  return (
    <Transition show={isOpen} as={Fragment}>
      <Dialog onClose={onClose} className="relative z-50">
        {/* Backdrop */}
        <TransitionChild
          as={Fragment}
          enter="ease-out duration-200"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm" />
        </TransitionChild>

        {/* Sliding panel */}
        <TransitionChild
          as={Fragment}
          enter="ease-out duration-200"
          enterFrom="-translate-x-full"
          enterTo="translate-x-0"
          leave="ease-in duration-200"
          leaveFrom="translate-x-0"
          leaveTo="-translate-x-full"
        >
          <DialogPanel className="fixed inset-y-0 left-0 w-[480px] overflow-y-auto border-r border-border-dark bg-surface-base shadow-elevated">
            <div className="sticky top-0 z-10 border-b border-border-dark bg-surface-base/90 px-4 py-3 backdrop-blur-sm">
              <h2 className="font-heading text-lg font-semibold text-white">
                Select Network
              </h2>
            </div>

            <div className="flex flex-col">
              {sortedNetworks.map((network) => (
                <button
                  key={network.chainId}
                  className={`flex w-full items-center justify-between px-4 py-2.5 text-left transition-colors hover:bg-accent-500/10 ${
                    selectedChainId === network.chainId.toString()
                      ? 'bg-accent-500/5 border-l-2 border-accent-500'
                      : 'border-l-2 border-transparent'
                  }`}
                  onClick={() => onPick(network)}
                >
                  <span className="mr-2 flex items-center gap-3 truncate">
                    <img
                      src={getApiUrl(`/image/${network.chainId}`)}
                      alt=""
                      width={24}
                      height={24}
                      className="inline-block rounded-full"
                      onError={(e) => {
                        ;(e.target as HTMLImageElement).style.display = 'none'
                      }}
                    />
                    <span className="text-white/90">{getNetworkName(network.chainId)}</span>
                  </span>
                  <span className="flex-shrink-0 whitespace-nowrap text-sm text-white/30">
                    Chain {network.chainId}
                  </span>
                </button>
              ))}
            </div>
          </DialogPanel>
        </TransitionChild>
      </Dialog>
    </Transition>
  )
}

// packages/ui/src/lib/components/NetworkSelect.svelte
<script lang="ts">
  import networkNames from '../networks.json' assert { type: 'json' }
  import { metrics } from '../stores/metrics.svelte'
  import { showTestnets } from '../stores/settings.svelte'
  import type { NetworkInfo } from '../types'
  import { Modal } from '@skeletonlabs/skeleton-svelte'

  type Props = {
    isOpenToStart: boolean
    network: NetworkInfo | null
    showTestnets: boolean
    onselect: (network: NetworkInfo) => void
    onnetworkname: (getName: (id: string | number) => string) => void
  }

  const { isOpenToStart, network: selectedNetwork, onselect, onnetworkname }: Props = $props()

  let isOpen = $state(isOpenToStart)

  // Add this to the existing onMount
  const storedChainId = localStorage.getItem('selectedChainId')
  if (storedChainId && metrics.value) {
    const network = metrics.value.networks.supported.find((n) => n.chainId.toString() === storedChainId)
    if (network) {
      onselect(network)
    }
    // Clear the stored chain ID after using it
    localStorage.removeItem('selectedChainId')
  }

  // Network name function for use in component and parent
  function getNetworkName(chainId: number | string): string {
    const chainIdStr = chainId.toString()
    // First check our priority networks to ensure specific naming
    const priorityNames: Record<string, string> = {
      '1': 'Ethereum',
      '369': 'PulseChain',
      '56': 'BNB Smart Chain',
      '137': 'Polygon',
      '42161': 'Arbitrum One',
      '10': 'Optimism',
      '100': 'Gnosis Chain',
      '324': 'zkSync Era',
      '534352': 'Scroll',
      '250': 'Fantom Opera',
      '1030': 'Conflux eSpace',
      '5000': 'Mantle',
      '8453': 'Base',
      '59144': 'Linea',
      '7777777': 'Zora',
    }

    // Use priority names first, then fall back to Uniswap names, then to generic Chain ID
    const networkName = priorityNames[chainIdStr] || networkNames[chainIdStr as keyof typeof networkNames]
    return networkName || `Chain ${chainIdStr}`
  }

  // Expose getNetworkName to parent
  $effect(() => {
    // dispatch('networkname', getNetworkName)
    onnetworkname(getNetworkName)
  })

  // Sort networks by priority and name
  function sortNetworks(networks: NetworkInfo[]): NetworkInfo[] {
    const priorityChains = ['1', '369'] // Ethereum and PulseChain first

    // Filter out testnets if showTestnets is false
    let filteredNetworks = networks
    if (!showTestnets.value) {
      filteredNetworks = networks.filter(
        (network) => !getNetworkName(network.chainId).toLowerCase().includes('testnet'),
      )
    }

    return [...filteredNetworks].sort((a, b) => {
      const aChainId = a.chainId.toString()
      const bChainId = b.chainId.toString()

      // Priority chains first
      const aIndex = priorityChains.indexOf(aChainId)
      const bIndex = priorityChains.indexOf(bChainId)

      if (aIndex !== -1 && bIndex === -1) return -1
      if (aIndex === -1 && bIndex !== -1) return 1
      if (aIndex !== -1 && bIndex !== -1) return aIndex - bIndex

      // Then sort by name
      return getNetworkName(a.chainId).localeCompare(getNetworkName(b.chainId))
    })
  }
</script>

<div class="relative w-full">
  <div class="mb-2 flex items-center justify-end">
    <label class="group flex cursor-pointer items-center gap-3 flex-row">
      <div class="relative flex">
        <input
          type="checkbox"
          class="peer sr-only"
          checked={showTestnets.value}
          onchange={(e) => {
            const target = e.target as HTMLInputElement
            showTestnets.value = target.checked
          }} />
        <div class="h-6 w-11 rounded-full bg-surface-300 dark:bg-surface-600 transition-colors peer-checked:bg-secondary-600/20"></div>
        <div
          class="absolute left-1 top-1 h-4 w-4 rounded-full bg-surface-100 transition-all peer-checked:translate-x-5 peer-checked:bg-secondary-600"
        ></div>
      </div>
      <span
        class="text-sm font-medium text-surface-600 transition-colors group-hover:text-secondary-600 dark:text-surface-300"
        >Show&nbsp;Testnets</span>
    </label>
  </div>
  <Modal
    open={isOpen}
    onOpenChange={(e) => (isOpen = e.open)}
    triggerBase="btn preset-tonal w-full justify-between px-3 py-2 text-left text-sm leading-6 border border-gray-500 hover:border-gray-400 items-center rounded-lg select-network"
    contentBase="bg-surface-100-900 space-y-4 shadow-xl w-[480px] h-screen left-0 overflow-y-auto"
    positionerJustify="justify-start"
    positionerAlign=""
    positionerPadding=""
    transitionsPositionerIn={{ x: -480, duration: 200 }}
    transitionsPositionerOut={{ x: -480, duration: 200 }}>
    {#snippet trigger()}
      {#if selectedNetwork}
        <span class="truncate">{getNetworkName(selectedNetwork.chainId)} (Chain ID: {selectedNetwork.chainId})</span>
      {:else}
        <span class="text-gray-500">Choose a network...</span>
      {/if}
      <i class="fas fa-chevron-down !m-0 flex-shrink-0 transition-transform flex items-center" class:rotate-180={isOpen}
      ></i>
    {/snippet}
    {#snippet content()}
      <article>
        {#if metrics.value}
          {#each sortNetworks(metrics.value.networks.supported) as network}
            <button
              class="flex w-full items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-secondary-600 dark:hover:bg-secondary-600"
              class:selected={selectedNetwork?.chainId === network.chainId}
              onclick={() => {
                isOpen = false
                onselect(network)
              }}>
              <span class="mr-2 truncate">{getNetworkName(network.chainId)}</span>
              <span class="flex-shrink-0 whitespace-nowrap text-surface-500">(Chain ID: {network.chainId})</span>
            </button>
          {/each}
        {/if}
      </article>
    {/snippet}
  </Modal>
</div>
