// packages/ui/src/lib/components/TokenPreview.svelte
<script lang="ts">
  import Image from './Image.svelte'
  import Icon from '@iconify/svelte'

  export let url: string = ''
  export let previewError = false
  export let iconExists = true
  export let isCircularCrop = false
  export let backgroundColor = '#2b4f54'
  export let showColorPicker = false

  let zoomLevel = 1
  let isDragging = false
  let startX = 0
  let startY = 0
  let translateX = 0
  let translateY = 0

  // Add reset function to restore initial state
  export function resetPreview() {
    zoomLevel = 1
    translateX = 0
    translateY = 0
    isCircularCrop = false
    showColorPicker = false
    backgroundColor = '#2b4f54'
    previewError = false
    iconExists = true
  }

  function handleZoomIn() {
    zoomLevel = Math.min(zoomLevel + 0.5, 4)
  }

  function handleZoomOut() {
    zoomLevel = Math.max(zoomLevel - 0.5, 0.5)
  }

  function handleMouseDown(event: MouseEvent) {
    isDragging = true
    startX = event.clientX - translateX
    startY = event.clientY - translateY
  }

  function handleMouseMove(event: MouseEvent) {
    if (!isDragging) return
    translateX = event.clientX - startX
    translateY = event.clientY - startY
  }

  function handleMouseUp() {
    isDragging = false
  }

  function handleWheel(event: WheelEvent) {
    event.preventDefault()
    const delta = -Math.sign(event.deltaY)
    const zoomStep = 0.1
    if (delta > 0) {
      zoomLevel = Math.min(zoomLevel + zoomStep, 4)
    } else {
      zoomLevel = Math.max(zoomLevel - zoomStep, 0.5)
    }
  }

  function handleColorInput(event: Event) {
    const input = event.target as HTMLInputElement
    backgroundColor = input.value
  }

  function handleColorTextInput(event: Event) {
    const input = event.target as HTMLInputElement
    const value = input.value.trim()
    // Support various color formats
    if (value.match(/^#[0-9A-Fa-f]{6}$/)) {
      backgroundColor = value
    } else if (value.match(/^rgb\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*\)$/)) {
      backgroundColor = value
    } else if (value.match(/^rgba\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*,\s*[\d.]+\s*\)$/)) {
      backgroundColor = value
    }
  }

  // Handle initial image load error
  function handleImageError() {
    previewError = true
    iconExists = false
  }
</script>

<div class="card variant-ghost space-y-2">
  <div class="flex items-center justify-between">
    <span class="label">Preview</span>
    <div class="flex gap-2">
      <button
        class="variant-soft-surface btn btn-sm"
        onclick={handleZoomOut}
        disabled={zoomLevel <= 0.5}
        aria-label="Zoom out">
        <i class="fas fa-minus"></i>
      </button>
      <span class="flex items-center px-2 text-sm">
        {Math.round(zoomLevel * 100)}%
      </span>
      <button
        class="variant-soft-surface btn btn-sm"
        onclick={handleZoomIn}
        disabled={zoomLevel >= 4}
        aria-label="Zoom in">
        <i class="fas fa-plus"></i>
      </button>
    </div>
  </div>
  <div class="flex flex-col justify-center">
    <button
      type="button"
      class="relative h-[300px] w-full cursor-move overflow-hidden {showColorPicker
        ? ''
        : 'checkerboard'} border border-surface-700/20"
      style="background-color: {showColorPicker ? backgroundColor : ''}"
      onmousedown={handleMouseDown}
      onmousemove={handleMouseMove}
      onmouseup={handleMouseUp}
      onmouseleave={handleMouseUp}
      onwheel={handleWheel}
      role="slider"
      aria-label="Token preview zoom control"
      aria-valuemin="50"
      aria-valuemax="400"
      aria-valuenow={Math.round(zoomLevel * 100)}
      aria-valuetext="{Math.round(zoomLevel * 100)}% zoom">
      <Image
        alt="Icon preview"
        src={url}
        class="user-drag-none absolute left-1/2 top-1/2 transition-transform duration-100 {isCircularCrop
          ? 'rounded-full'
          : ''}"
        style="transform: translate(calc(-50% + {translateX}px), calc(-50% + {translateY}px)) scale({zoomLevel})"
        size={64}
        onerror={handleImageError}>
        {#snippet fallback()}
          <Icon icon="nrk:404" class="h-12 w-12" />
        {/snippet}
      </Image>
    </button>
    <div class="mt-2 text-center text-sm text-gray-400">
      <span class="opacity-75">Click and drag to pan • Scroll to zoom</span>
    </div>
  </div>
</div>

<!-- Preview Options -->
<div class="card variant-ghost space-y-4">
  <span class="label">Preview Options</span>
  <div class="flex flex-col gap-4">
    <!-- Crop Option -->
    <div class="flex items-center gap-2">
      <button
        class="variant-soft btn btn-sm transition-all {isCircularCrop ? 'shadow-lg shadow-[#00DC82]/15' : ''}"
        onclick={() => (isCircularCrop = !isCircularCrop)}>
        <i class="fas fa-circle mr-2"></i>
        Circle Crop
      </button>
    </div>

    <!-- Background Options -->
    <div class="space-y-2">
      <div class="flex items-center gap-2">
        <button
          class="variant-soft btn btn-sm transition-all {showColorPicker ? 'shadow-lg shadow-[#00DC82]/15' : ''}"
          onclick={() => (showColorPicker = !showColorPicker)}>
          <i class="fas fa-fill-drip mr-2"></i>
          {showColorPicker ? 'Hide Color Options' : 'Custom Background'}
        </button>
      </div>

      {#if showColorPicker}
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
          <!-- Color Picker -->
          <div class="space-y-2">
            <label for="color-picker" class="text-sm">Pick a color:</label>
            <input
              id="color-picker"
              type="color"
              class="h-10 w-full cursor-pointer rounded"
              value={backgroundColor}
              oninput={handleColorInput} />
          </div>

          <!-- Color Input -->
          <div class="space-y-2">
            <label for="color-text" class="text-sm">Or enter a color value:</label>
            <input
              id="color-text"
              type="text"
              class="input"
              placeholder="#HEX, rgb(), rgba()"
              value={backgroundColor}
              oninput={handleColorTextInput} />
            <p class="text-xs opacity-75"> Supports HEX (#RRGGBB), RGB (rgb(r,g,b)), and RGBA (rgba(r,g,b,a)) </p>
          </div>
        </div>
      {/if}
    </div>
  </div>
</div>

<style lang="postcss">
  @reference 'tailwindcss';
  /* Checkerboard pattern for transparent image background */
  .checkerboard {
    background-color: #fff;
    background-image:
      linear-gradient(45deg, #ddd 25%, transparent 25%), linear-gradient(-45deg, #ddd 25%, transparent 25%),
      linear-gradient(45deg, transparent 75%, #ddd 75%), linear-gradient(-45deg, transparent 75%, #ddd 75%);
    background-size: 16px 16px;
    background-position:
      0 0,
      0 8px,
      8px -8px,
      -8px 0px;
  }

  /* Dark mode version - using more subtle colors */
  :global(.dark) .checkerboard {
    background-color: #1a1a1a;
    background-image:
      linear-gradient(45deg, #252525 25%, transparent 25%), linear-gradient(-45deg, #252525 25%, transparent 25%),
      linear-gradient(45deg, transparent 75%, #252525 75%), linear-gradient(-45deg, transparent 75%, #252525 75%);
  }

  :global(.user-drag-none) {
    -webkit-user-drag: none;
    user-select: none;
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
  }
</style>

// packages/ui/src/lib/components/TokenPreview.tsx
import {
  useState,
  useCallback,
  forwardRef,
  useImperativeHandle,
  type MouseEvent as ReactMouseEvent,
  type WheelEvent as ReactWheelEvent,
} from 'react'
import { Icon } from '@iconify/react'
import Image from './Image'

export interface TokenPreviewHandle {
  resetPreview: () => void
}

interface TokenPreviewProps {
  url: string
  previewError: boolean
  iconExists: boolean
  isCircularCrop: boolean
  backgroundColor: string
  showColorPicker: boolean
  setPreviewError: (value: boolean) => void
  setIconExists: (value: boolean) => void
  setIsCircularCrop: (value: boolean) => void
  setBackgroundColor: (value: string) => void
  setShowColorPicker: (value: boolean) => void
}

const TokenPreview = forwardRef<TokenPreviewHandle, TokenPreviewProps>(
  function TokenPreview(
    {
      url,
      previewError,
      iconExists,
      isCircularCrop,
      backgroundColor,
      showColorPicker,
      setPreviewError,
      setIconExists,
      setIsCircularCrop,
      setBackgroundColor,
      setShowColorPicker,
    },
    ref,
  ) {
    const [zoomLevel, setZoomLevel] = useState(1)
    const [isDragging, setIsDragging] = useState(false)
    const [startX, setStartX] = useState(0)
    const [startY, setStartY] = useState(0)
    const [translateX, setTranslateX] = useState(0)
    const [translateY, setTranslateY] = useState(0)

    useImperativeHandle(ref, () => ({
      resetPreview() {
        setZoomLevel(1)
        setTranslateX(0)
        setTranslateY(0)
        setIsCircularCrop(false)
        setShowColorPicker(false)
        setBackgroundColor('#2b4f54')
        setPreviewError(false)
        setIconExists(true)
      },
    }))

    const handleZoomIn = useCallback(() => {
      setZoomLevel((prev) => Math.min(prev + 0.5, 4))
    }, [])

    const handleZoomOut = useCallback(() => {
      setZoomLevel((prev) => Math.max(prev - 0.5, 0.5))
    }, [])

    const handleMouseDown = useCallback(
      (event: ReactMouseEvent) => {
        setIsDragging(true)
        setStartX(event.clientX - translateX)
        setStartY(event.clientY - translateY)
      },
      [translateX, translateY],
    )

    const handleMouseMove = useCallback(
      (event: ReactMouseEvent) => {
        if (!isDragging) return
        setTranslateX(event.clientX - startX)
        setTranslateY(event.clientY - startY)
      },
      [isDragging, startX, startY],
    )

    const handleMouseUp = useCallback(() => {
      setIsDragging(false)
    }, [])

    const handleWheel = useCallback((event: ReactWheelEvent) => {
      event.preventDefault()
      const delta = -Math.sign(event.deltaY)
      const zoomStep = 0.1
      if (delta > 0) {
        setZoomLevel((prev) => Math.min(prev + zoomStep, 4))
      } else {
        setZoomLevel((prev) => Math.max(prev - zoomStep, 0.5))
      }
    }, [])

    const handleColorInput = useCallback(
      (event: React.FormEvent<HTMLInputElement>) => {
        setBackgroundColor(event.currentTarget.value)
      },
      [setBackgroundColor],
    )

    const handleColorTextInput = useCallback(
      (event: React.FormEvent<HTMLInputElement>) => {
        const value = event.currentTarget.value.trim()
        if (value.match(/^#[0-9A-Fa-f]{6}$/)) {
          setBackgroundColor(value)
        } else if (value.match(/^rgb\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*\)$/)) {
          setBackgroundColor(value)
        } else if (
          value.match(/^rgba\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*,\s*[\d.]+\s*\)$/)
        ) {
          setBackgroundColor(value)
        }
      },
      [setBackgroundColor],
    )

    const handleImageError = useCallback(() => {
      setPreviewError(true)
      setIconExists(false)
    }, [setPreviewError, setIconExists])

    return (
      <>
        {/* Preview card */}
        <div className="card variant-ghost space-y-2">
          <div className="flex items-center justify-between">
            <span className="label">Preview</span>
            <div className="flex gap-2">
              <button
                className="variant-soft-surface btn btn-sm"
                onClick={handleZoomOut}
                disabled={zoomLevel <= 0.5}
                aria-label="Zoom out"
              >
                <i className="fas fa-minus"></i>
              </button>
              <span className="flex items-center px-2 text-sm">
                {Math.round(zoomLevel * 100)}%
              </span>
              <button
                className="variant-soft-surface btn btn-sm"
                onClick={handleZoomIn}
                disabled={zoomLevel >= 4}
                aria-label="Zoom in"
              >
                <i className="fas fa-plus"></i>
              </button>
            </div>
          </div>
          <div className="flex flex-col justify-center">
            <button
              type="button"
              className={`relative h-[300px] w-full cursor-move overflow-hidden ${showColorPicker ? '' : 'checkerboard'} border border-surface-700/20`}
              style={{
                backgroundColor: showColorPicker ? backgroundColor : undefined,
              }}
              onMouseDown={handleMouseDown}
              onMouseMove={handleMouseMove}
              onMouseUp={handleMouseUp}
              onMouseLeave={handleMouseUp}
              onWheel={handleWheel}
              role="slider"
              aria-label="Token preview zoom control"
              aria-valuemin={50}
              aria-valuemax={400}
              aria-valuenow={Math.round(zoomLevel * 100)}
              aria-valuetext={`${Math.round(zoomLevel * 100)}% zoom`}
            >
              <Image
                alt="Icon preview"
                src={url}
                className={`user-drag-none absolute left-1/2 top-1/2 transition-transform duration-100 ${isCircularCrop ? 'rounded-full' : ''}`}
                style={{
                  transform: `translate(calc(-50% + ${translateX}px), calc(-50% + ${translateY}px)) scale(${zoomLevel})`,
                }}
                size={64}
                onError={handleImageError}
                fallback={() => <Icon icon="nrk:404" className="h-12 w-12" />}
              />
            </button>
            <div className="mt-2 text-center text-sm text-gray-400">
              <span className="opacity-75">
                Click and drag to pan &bull; Scroll to zoom
              </span>
            </div>
          </div>
        </div>

        {/* Preview Options */}
        <div className="card variant-ghost space-y-4">
          <span className="label">Preview Options</span>
          <div className="flex flex-col gap-4">
            {/* Crop Option */}
            <div className="flex items-center gap-2">
              <button
                className={`variant-soft btn btn-sm transition-all ${isCircularCrop ? 'shadow-lg shadow-[#00DC82]/15' : ''}`}
                onClick={() => setIsCircularCrop(!isCircularCrop)}
              >
                <i className="fas fa-circle mr-2"></i>
                Circle Crop
              </button>
            </div>

            {/* Background Options */}
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <button
                  className={`variant-soft btn btn-sm transition-all ${showColorPicker ? 'shadow-lg shadow-[#00DC82]/15' : ''}`}
                  onClick={() => setShowColorPicker(!showColorPicker)}
                >
                  <i className="fas fa-fill-drip mr-2"></i>
                  {showColorPicker ? 'Hide Color Options' : 'Custom Background'}
                </button>
              </div>

              {showColorPicker && (
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                  {/* Color Picker */}
                  <div className="space-y-2">
                    <label htmlFor="color-picker" className="text-sm">
                      Pick a color:
                    </label>
                    <input
                      id="color-picker"
                      type="color"
                      className="h-10 w-full cursor-pointer rounded"
                      value={backgroundColor}
                      onInput={handleColorInput}
                    />
                  </div>

                  {/* Color Input */}
                  <div className="space-y-2">
                    <label htmlFor="color-text" className="text-sm">
                      Or enter a color value:
                    </label>
                    <input
                      id="color-text"
                      type="text"
                      className="input"
                      placeholder="#HEX, rgb(), rgba()"
                      value={backgroundColor}
                      onInput={handleColorTextInput}
                    />
                    <p className="text-xs opacity-75">
                      Supports HEX (#RRGGBB), RGB (rgb(r,g,b)), and RGBA
                      (rgba(r,g,b,a))
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </>
    )
  },
)

export default TokenPreview
