// frontend/src/lib/components/TokenAddressInput.svelte
<script lang="ts">
  type Props = {
    address: string
    oninput: (addr: string) => void
    onback: () => void
  }
  const { oninput, onback, address }: Props = $props()

  let tokenAddress = $state('')
  $effect(() => {
    tokenAddress = address
  })

  function handleInput(e: Event) {
    const input = e.target as HTMLInputElement
    tokenAddress = input.value.trim()
    oninput(tokenAddress)
  }

</script>

<div class="space-y-2">
  <div class="flex items-center justify-between">
    <label for="token-address" class="label">Token Address</label>
    <button class="variant-filled-primary btn btn-sm" onclick={onback}>
      <i class="fas fa-arrow-left mr-2"></i>
      Back to Token Browser
    </button>
  </div>
  <input
    id="token-address"
    type="text"
    class="input"
    placeholder="0x..."
    value={tokenAddress}
    oninput={handleInput} />
</div>

<style lang="postcss">
  .label {
    @apply text-sm font-medium;
  }
</style>

// packages/ui/src/lib/components/TokenAddressInput.tsx
import { useState, useEffect } from 'react'

interface TokenAddressInputProps {
  address: string
  onInput: (addr: string) => void
  onBack: () => void
}

export default function TokenAddressInput({
  address,
  onInput,
  onBack,
}: TokenAddressInputProps) {
  const [tokenAddress, setTokenAddress] = useState('')

  useEffect(() => {
    setTokenAddress(address)
  }, [address])

  function handleInput(e: React.ChangeEvent<HTMLInputElement>) {
    const value = e.target.value.trim()
    setTokenAddress(value)
    onInput(value)
  }

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <label htmlFor="token-address" className="text-sm font-medium">
          Token Address
        </label>
        <button className="variant-filled-primary btn btn-sm" onClick={onBack}>
          <i className="fas fa-arrow-left mr-2"></i>
          Back to Token Browser
        </button>
      </div>
      <input
        id="token-address"
        type="text"
        className="input"
        placeholder="0x..."
        value={tokenAddress}
        onChange={handleInput}
      />
    </div>
  )
}
