// packages/ui/src/App.tsx
import { HashRouter, Routes, Route } from 'react-router-dom'
import { ThemeProvider } from './lib/contexts/ThemeContext'
import { SettingsProvider } from './lib/contexts/SettingsContext'
import { MetricsProvider } from './lib/contexts/MetricsContext'
import { Layout } from './Layout'
import Home from './lib/pages/Home'

function Wizard() {
  return <div>Wizard page placeholder</div>
}

function Docs() {
  return <div>Docs page placeholder</div>
}

export function App() {
  return (
    <ThemeProvider>
      <SettingsProvider>
        <MetricsProvider>
          <HashRouter>
            <Routes>
              <Route element={<Layout />}>
                <Route path="/" element={<Home />} />
                <Route path="/wizard" element={<Wizard />} />
                <Route path="/docs" element={<Docs />} />
              </Route>
            </Routes>
          </HashRouter>
        </MetricsProvider>
      </SettingsProvider>
    </ThemeProvider>
  )
}

// packages/frontend/src/App.svelte
<script lang="ts">
  import Layout from './Layout.svelte'
  import { page } from './lib/stores/page.svelte'
  import Home from './lib/pages/page.svelte'
  import Wizard from './lib/pages/wizard/page.svelte'
  import Docs from './lib/pages/docs/page.svelte'
</script>

<Layout>
  {#if page.route.id === '/'}
  <Home />
  {:else if page.route.id === '/wizard'}
  <Wizard />
  {:else if page.route.id === '/docs'}
  <Docs />
  {/if}
</Layout>
