// packages/frontend/src/lib/pages/wizard/page.svelte
<script lang="ts">
  import ApiTypeSelector from '../../components/ApiTypeSelector.svelte'
  import ErrorMessage from '../../components/ErrorMessage.svelte'
  import NetworkSelect from '../../components/NetworkSelect.svelte'
  import TokenAddressInput from '../../components/TokenAddressInput.svelte'
  import TokenBrowser from '../../components/TokenBrowser.svelte'
  import TokenListSelector from '../../components/TokenListSelector.svelte'
  import TokenPreview from '../../components/TokenPreview.svelte'
  import UrlDisplay from '../../components/UrlDisplay.svelte'
  import { metrics } from '../../stores/metrics.svelte'
  import { showTestnets } from '../../stores/settings.svelte'
  import type { ApiType, NetworkInfo, Token, SearchUpdate } from '../../types'
  import { getApiUrl, initializeApiBase } from '../../utils'
  import { onMount } from 'svelte'
  import TokenSearch from '../../components/TokenSearch.svelte'
  import { enabledLists, tokensByList } from '../../stores/token-browser.svelte'
  import _ from 'lodash'

  let getNetworkName: (chainId: number | string) => string = $state((chainId) => `Chain ${chainId}`)
  let selectedChain: number | null = $state(null)
  let tokenAddress: string = $state('')
  let urlType = $state<ApiType>('token')
  let listName: string = $state('default')
  let generatedUrl: string = $state('')
  let previewError = $state(false)
  let iconExists = $state(true)
  let isCircularCrop = $state(false)
  let showTokenBrowser = $state(true)
  let tokenPreviewComponent: TokenPreview | null = $state(null)
  let currentSearchState = $state<SearchUpdate | null>(null)

  let availableLists: Array<{
    key: string
    name: string
    providerKey: string
    chainId: string
    type: string
    default: boolean
  }> = $state([])

  let selectedList: { key: string; providerKey: string } | null = $state(null)
  let selectedNetwork: NetworkInfo | null = $state(null)

  // TokenBrowser state
  let filteredTokens = $state<Token[]>([])
  let isListFilterOpen = $state(false)
  let searchQuery = $state('')
  let isGlobalSearchActive = $state(false)
  let globalSearchResults: Token[] = $state([])
  let currentPage = $state(1)
  let tokensPerPage = $state(25)
  let backgroundColor = $state('#2b4f54')
  let showColorPicker = $state(false)

  // Add missing state
  let allTokens = $state<Token[]>([])

  let isInitialized = $state(false)

  // Add URL cleanup on mount
  onMount(() => {
    let cancelled = false

    // Handle async initialization
    const initialize = async () => {
      await initializeApiBase()
      if (!cancelled) {
        isInitialized = true
        // Clean up URL if it contains a hash
        metrics.fetchMetrics()

        // First fetch available lists
        try {
          const response = await fetch(getApiUrl('/list'))
          if (!cancelled && response.ok) {
            const data = await response.json()
            if (!cancelled) {
              // Transform the data into the format we need, removing duplicates
              const uniqueLists = new Map()
              data.forEach((info: any) => {
                const key = `${info.providerKey}-${info.key}-${info.chainId}`
                if (!uniqueLists.has(key)) {
                  uniqueLists.set(key, {
                    key: info.key,
                    name: info.name || info.key,
                    providerKey: info.providerKey,
                    chainId: info.chainId?.toString() || '0',
                    type: info.type || 'hosted',
                    default: info.default || false,
                  })
                }
              })
              availableLists = Array.from(uniqueLists.values())
            }
          }
        } catch (error) {
          console.error('Failed to fetch available lists:', error)
        }

        // Now check for selected network after lists are loaded
        if (selectedNetwork) {
          tryFetchTokenLists(selectedNetwork.chainId)
        }
      }
    }

    initialize()

    return () => {
      cancelled = true
    }
  })

  // Add this reactive statement
  $effect(() => {
    if (selectedNetwork && urlType === 'token') {
      tryFetchTokenLists(selectedNetwork.chainId)
    }
  })

  function generateUrl() {
    previewError = false
    iconExists = true

    switch (urlType) {
      case 'network':
        if (selectedChain) {
          generatedUrl = getApiUrl(`/image/${selectedChain}`)
        }
        break
      case 'token':
        if (selectedChain && tokenAddress) {
          generatedUrl = getApiUrl(`/image/${selectedChain}/${tokenAddress}`)
        }
        break
      case 'list':
        if (selectedChain) {
          // Split listName into provider and key parts
          const [providerKey, listKey = 'default'] = listName.split('/')
          generatedUrl = getApiUrl(`/list/${providerKey}/${listKey}?chainId=${selectedChain}`)
        } else {
          const [providerKey, listKey = 'default'] = listName.split('/')
          generatedUrl = getApiUrl(`/list/${providerKey}/${listKey}`)
        }
        break
    }
  }

  function resetForm() {
    if (urlType === 'token' && tokenAddress) {
      // Only reset the preview state, maintaining token selection
      if (tokenPreviewComponent) {
        tokenPreviewComponent.resetPreview()
      }
      generateUrl() // Regenerate the URL to refresh the preview
    } else {
      // Full reset
      selectedChain = null
      tokenAddress = ''
      generatedUrl = ''
      previewError = false
      if (tokenPreviewComponent) {
        tokenPreviewComponent.resetPreview()
      }
    }
  }

  function selectNetwork(network: NetworkInfo) {
    selectedChain = network.chainId
    selectedNetwork = network
    generateUrl()
    // Fetch token lists when in token mode
    if (urlType === 'token') {
      tryFetchTokenLists(network.chainId)
    }
  }

  function filterTokens() {
    const searchTerm = searchQuery.toLowerCase()
    if (!isGlobalSearchActive) {
      // Filter only tokens from the selected chain
      filteredTokens = allTokens.filter(
        (token) =>
          token.chainId.toString() === selectedChain?.toString() &&
          (token.name.toLowerCase().includes(searchTerm) ||
            token.symbol.toLowerCase().includes(searchTerm) ||
            token.address.toLowerCase().includes(searchTerm)),
      )
    } else {
      // Use global search results
      filteredTokens = globalSearchResults
    }
  }

  function handleTokenListToggle(listKey: string, enabled: boolean) {
    if (enabled) {
      enabledLists.add(listKey)
    } else {
      enabledLists.delete(listKey)
    }
    updateCombinedTokenList()
  }

  function handleTokenListToggleAll(enabled: boolean) {
    const listsToToggle = Array.from(tokensByList.entries())
      .filter(([_, tokens]) => tokens.length > 0)
      .map(([key]) => key)

    if (enabled) {
      listsToToggle.forEach((key) => enabledLists.add(key))
    } else {
      listsToToggle.forEach((key) => enabledLists.delete(key))
    }
    updateCombinedTokenList()
  }

  async function tryFetchTokenLists(chainId: number) {
    // Get relevant lists for the chain
    const relevantLists = availableLists.filter((list) => list.chainId === chainId.toString() || list.chainId === '0')

    // Clear previous tokens
    tokensByList.clear()
    enabledLists.clear()
    allTokens = []
    filteredTokens = []

    // Process lists in parallel but with controlled concurrency
    const processInBatches = async () => {
      const batchSize = 2
      for (let i = 0; i < relevantLists.length; i += batchSize) {
        const batch = relevantLists.slice(i, i + batchSize)
        await Promise.all(batch.map((list) => processListWithRetry(list, chainId)))
      }
    }

    // Start processing in the background
    processInBatches()
  }

  function updateCombinedTokenList() {
    // Create a Map to deduplicate tokens by address
    const tokenMap = new Map<string, any>()

    // First add non-bridge tokens
    for (const [listKey, tokens] of tokensByList.entries()) {
      if (enabledLists.has(listKey) && !listKey.includes('bridge')) {
        for (const token of tokens) {
          const key = `${token.chainId}-${token.address.toLowerCase()}`
          if (!tokenMap.has(key) && token.hasIcon) {
            tokenMap.set(key, token)
          }
        }
      }
    }

    // Then add bridge tokens only if they don't already exist
    for (const [listKey, tokens] of tokensByList.entries()) {
      if (enabledLists.has(listKey) && listKey.includes('bridge')) {
        for (const token of tokens) {
          const key = `${token.chainId}-${token.address.toLowerCase()}`
          if (!tokenMap.has(key) && token.hasIcon) {
            tokenMap.set(key, token)
          }
        }
      }
    }

    allTokens = Array.from(tokenMap.values())
    filteredTokens = allTokens.filter((token) => token.chainId.toString() === selectedChain?.toString())
    currentPage = 1
  }

  async function processListWithRetry(list: (typeof availableLists)[0], chainId: number) {
    try {
      // Add chainId parameter for chain-specific lists
      const url =
        list.chainId === '0'
          ? getApiUrl(`/list/${list.providerKey}/${list.key}`)
          : getApiUrl(`/list/${list.providerKey}/${list.key}?chainId=${chainId}`)

      const response = await fetch(url)

      if (response.ok) {
        const data = await response.json()
        if (data?.tokens && Array.isArray(data.tokens)) {
          const tokens = data.tokens.map((token: any) => ({
            ...token,
            hasIcon: true,
            sourceList: `${list.providerKey}/${list.key}`,
            isBridgeToken: list.providerKey.includes('bridge'),
          }))

          const listKey = `${list.providerKey}/${list.key}`
          tokensByList.set(listKey, tokens)
          enabledLists.add(listKey)
          updateCombinedTokenList()
        }
      } else if (response.status === 404) {
        // List not found - log but don't treat as error
        console.log(`List ${list.providerKey}/${list.key} not available for chain ${chainId}`)
        // Remove from enabled lists if it was previously enabled
        const listKey = `${list.providerKey}/${list.key}`
        enabledLists.delete(listKey)
        tokensByList.delete(listKey)
        updateCombinedTokenList()
      } else {
        console.error(`Failed to fetch list ${list.providerKey}/${list.key}: ${response.status} ${response.statusText}`)
      }
    } catch (error) {
      console.error(`Network error fetching list ${list.name}:`, error)
    }
  }
  const list = $derived(Array.from(tokensByList.entries()))
  const underChain = $derived(getListsWithTokensForChain(list, selectedChain))
  const listCount = $derived(underChain.length)
  const tokenCount = $derived(
    _(underChain)
      .flatMap(([, tkns]) => tkns)
      .uniqBy((v) => v.address.toLowerCase())
      .value().length,
  )

  function getListsWithTokensForChain(list: [string, Token[]][], selectedChain: number | null) {
    return list.filter(([_, tokens]) => {
      const tokensForNetwork = tokens.filter((token) => token.chainId === selectedChain)
      return tokensForNetwork.length > 0
    })
  }
</script>

{#if !isInitialized}
  <div class="flex min-h-screen items-center justify-center">
    <div class="space-y-4 text-center">
      <div class="loading loading-spinner loading-lg"></div>
      <p>Initializing...</p>
    </div>
  </div>
{:else}
  <div class="container mx-auto max-w-3xl space-y-8 p-4 sm:p-8">
    <div class="space-y-4 text-center">
      <h1 class="h1">URL Wizard</h1>
      <p class="text-lg">Generate URLs for the Gib Assets API</p>
    </div>

    <div class="card space-y-6 p-4 sm:p-6">
      <!-- API Type Selection -->
      <ApiTypeSelector
        {urlType}
        network={selectedNetwork}
        onselect={() => {
          generatedUrl = ''
          previewError = false
          showTokenBrowser = urlType === 'token'
          // Reset token selection
          tokenAddress = ''
        }}
        onloadtokens={() => {
          // If we have a selected network, reload its tokens
          if (selectedNetwork) {
            tryFetchTokenLists(selectedNetwork.chainId)
          }
        }}
        ongenerate={() => {
          // Generate URL for network icon
          if (selectedNetwork) {
            generateUrl()
          }
        }}
        onreset={() => {
          generatedUrl = ''
          tokenAddress = ''
          previewError = false
        }} />

      <!-- Token List Selection (only for list type) -->
      {#if urlType === 'list'}
        <TokenListSelector
          {availableLists}
          bind:selectedList
          on:select={({ detail }) => {
            listName = `${detail.providerKey}/${detail.key}`
            generateUrl()
          }} />
      {/if}

      <!-- Network Selection -->
      <NetworkSelect
        isOpenToStart={false}
        network={selectedNetwork}
        showTestnets={showTestnets.value}
        onnetworkname={(fn) => (getNetworkName = fn)}
        onselect={selectNetwork} />

      <!-- Token Browser (show when network is selected in token mode) -->
      {#if urlType === 'token' && selectedNetwork && !tokenAddress}
        {@const networkName = selectedNetwork ? getNetworkName(selectedNetwork.chainId) : ''}
        <TokenBrowser
          {networkName}
          {filteredTokens}
          {isCircularCrop}
          {currentPage}
          {tokensPerPage}
          onpagechange={(page) => {
            currentPage = page
          }}
          onperpageupdate={(perPage) => {
            tokensPerPage = perPage
          }}
          onselecttoken={(token) => {
            tokenAddress = token.address
            generateUrl()
          }}>
          <TokenSearch
            count={tokenCount}
            {networkName}
            onsearchupdate={(searchState) => {
              currentSearchState = searchState
            }}
            {selectedChain}
            ontogglelist={handleTokenListToggle}
            ontoggleall={handleTokenListToggleAll}
            onupdateopen={(open) => {
              isListFilterOpen = open
            }} />
        </TokenBrowser>
      {/if}

      <!-- Manual Token Input -->
      {#if urlType === 'token' && selectedNetwork && tokenAddress}
        <TokenAddressInput
          address={tokenAddress}
          onback={() => {
            tokenAddress = ''
            generatedUrl = ''
            previewError = false
            iconExists = true
          }}
          oninput={(address) => {
            tokenAddress = address
            generateUrl()
          }} />
      {/if}

      <!-- Generated URL Display -->
      {#if generatedUrl}
        <UrlDisplay url={generatedUrl} />

        <!-- Preview -->
        {#if urlType !== 'list' && previewError}
          <ErrorMessage
            {urlType}
            chainId={selectedNetwork?.chainId}
            networkName={getNetworkName(selectedNetwork?.chainId || '')}
            {tokenAddress}
            {generatedUrl} />
        {:else if urlType !== 'list' && ((!showTokenBrowser && urlType === 'network') || (urlType === 'token' && tokenAddress))}
          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <span class="label">Preview</span>
            </div>
            <TokenPreview
              url={generatedUrl}
              bind:this={tokenPreviewComponent}
              bind:previewError
              bind:iconExists
              bind:isCircularCrop
              bind:backgroundColor
              bind:showColorPicker />
            {#if filteredTokens.length > 0}
              <div class="text-center text-sm text-surface-600 dark:text-surface-300">
                {filteredTokens.find((t) => t.address.toLowerCase() === tokenAddress.toLowerCase())?.name ||
                  'Unknown Token'}
              </div>
            {/if}
          </div>
        {/if}

        <!-- Reset Button -->
        <button class="variant-ghost-surface btn w-full" type="button" onclick={resetForm}>
          <i class="fas fa-redo mr-2"></i>
          Reset
        </button>
      {/if}
    </div>

    <!-- API Documentation Link -->
    <div class="text-center">
      <a href="#/docs" class="variant-ghost-surface btn">
        <i class="fas fa-book mr-2"></i>
        View Full API Documentation
      </a>
    </div>
  </div>
{/if}
<!--
<style lang="postcss">
  /* Add smooth hover effects for cards */
  .card {
    @apply transition-all duration-200;
  }
</style> -->

// packages/ui/src/lib/pages/Wizard.tsx
import { useState, useEffect, useRef, useMemo, useCallback } from 'react'
import type { ApiType, NetworkInfo, Token, SearchUpdate } from '../types'
import { getApiUrl, initializeApiBase } from '../utils'
import { useSettings } from '../contexts/SettingsContext'
import { useMetricsContext } from '../contexts/MetricsContext'
import { useTokenBrowser } from '../hooks/useTokenBrowser'
import ApiTypeSelector from '../components/ApiTypeSelector'
import NetworkSelect from '../components/NetworkSelect'
import TokenBrowser from '../components/TokenBrowser'
import TokenSearch from '../components/TokenSearch'
import TokenAddressInput from '../components/TokenAddressInput'
import TokenListSelector from '../components/TokenListSelector'
import TokenPreview, { type TokenPreviewHandle } from '../components/TokenPreview'
import UrlDisplay from '../components/UrlDisplay'
import ErrorMessage from '../components/ErrorMessage'
import _ from 'lodash'

interface AvailableList {
  key: string
  name: string
  providerKey: string
  chainId: string
  type: string
  default: boolean
}

export default function Wizard() {
  const { showTestnets: _showTestnets } = useSettings()
  const { fetchMetrics } = useMetricsContext()

  const { enabledLists, tokensByList, toggleList, toggleAll, setListTokens, clearTokens } =
    useTokenBrowser()

  const previewRef = useRef<TokenPreviewHandle>(null)

  // Core state
  const [selectedChain, setSelectedChain] = useState<number | null>(null)
  const [selectedNetwork, setSelectedNetwork] = useState<NetworkInfo | null>(null)
  const [urlType, setUrlType] = useState<ApiType>('token')
  const [tokenAddress, setTokenAddress] = useState('')
  const [generatedUrl, setGeneratedUrl] = useState('')
  const [listName, setListName] = useState('default')

  // Preview state
  const [previewError, setPreviewError] = useState(false)
  const [iconExists, setIconExists] = useState(true)
  const [isCircularCrop, setIsCircularCrop] = useState(false)
  const [backgroundColor, setBackgroundColor] = useState('#2b4f54')
  const [showColorPicker, setShowColorPicker] = useState(false)

  // Token browser state
  const [_allTokens, setAllTokens] = useState<Token[]>([])
  const [filteredTokens, setFilteredTokens] = useState<Token[]>([])
  const [currentPage, setCurrentPage] = useState(1)
  const [tokensPerPage, setTokensPerPage] = useState(25)
  const [_currentSearchState, setCurrentSearchState] = useState<SearchUpdate | null>(null)

  // Lists state
  const [availableLists, setAvailableLists] = useState<AvailableList[]>([])
  const [selectedList, setSelectedList] = useState<{ key: string; providerKey: string } | null>(
    null,
  )

  // Initialization
  const [isInitialized, setIsInitialized] = useState(false)

  // Network name resolver
  const [getNetworkNameFn, setGetNetworkNameFn] = useState<(id: string | number) => string>(
    () => (chainId: string | number) => `Chain ${chainId}`,
  )

  // Ref to hold availableLists for use inside the chain-fetch effect without
  // re-triggering it every time the list changes.
  const availableListsRef = useRef<AvailableList[]>([])
  availableListsRef.current = availableLists

  // Ref-backed helpers so callbacks always see the latest state without
  // needing those values in dependency arrays.
  const enabledListsRef = useRef(enabledLists)
  enabledListsRef.current = enabledLists

  const tokensByListRef = useRef(tokensByList)
  tokensByListRef.current = tokensByList

  const selectedChainRef = useRef(selectedChain)
  selectedChainRef.current = selectedChain

  // ---------------------------------------------------------------------------
  // URL Generation
  // ---------------------------------------------------------------------------

  const generateUrl = useCallback(
    (overrides?: { chain?: number | null; address?: string; type?: ApiType; list?: string }) => {
      const chain = overrides?.chain ?? selectedChain
      const address = overrides?.address ?? tokenAddress
      const type = overrides?.type ?? urlType
      const list = overrides?.list ?? listName

      setPreviewError(false)
      setIconExists(true)

      switch (type) {
        case 'network':
          if (chain) {
            setGeneratedUrl(getApiUrl(`/image/${chain}`))
          }
          break
        case 'token':
          if (chain && address) {
            setGeneratedUrl(getApiUrl(`/image/${chain}/${address}`))
          }
          break
        case 'list': {
          const [providerKey, listKey = 'default'] = list.split('/')
          if (chain) {
            setGeneratedUrl(getApiUrl(`/list/${providerKey}/${listKey}?chainId=${chain}`))
          } else {
            setGeneratedUrl(getApiUrl(`/list/${providerKey}/${listKey}`))
          }
          break
        }
      }
    },
    [selectedChain, tokenAddress, urlType, listName],
  )

  // ---------------------------------------------------------------------------
  // Token list combining / dedup
  // ---------------------------------------------------------------------------

  const updateCombinedTokenList = useCallback(() => {
    const currentEnabledLists = enabledListsRef.current
    const currentTokensByList = tokensByListRef.current
    const chain = selectedChainRef.current

    const tokenMap = new Map<string, Token>()

    // First add non-bridge tokens
    for (const [listKey, tokens] of currentTokensByList.entries()) {
      if (currentEnabledLists.has(listKey) && !listKey.includes('bridge')) {
        for (const token of tokens) {
          const key = `${token.chainId}-${token.address.toLowerCase()}`
          if (!tokenMap.has(key) && token.hasIcon) {
            tokenMap.set(key, token)
          }
        }
      }
    }

    // Then add bridge tokens only if they don't already exist
    for (const [listKey, tokens] of currentTokensByList.entries()) {
      if (currentEnabledLists.has(listKey) && listKey.includes('bridge')) {
        for (const token of tokens) {
          const key = `${token.chainId}-${token.address.toLowerCase()}`
          if (!tokenMap.has(key) && token.hasIcon) {
            tokenMap.set(key, token)
          }
        }
      }
    }

    const combined = Array.from(tokenMap.values())
    setAllTokens(combined)
    setFilteredTokens(combined.filter((token) => token.chainId.toString() === chain?.toString()))
    setCurrentPage(1)
  }, [])

  // ---------------------------------------------------------------------------
  // Fetch a single token list with error handling
  // ---------------------------------------------------------------------------

  const processListWithRetry = useCallback(
    async (list: AvailableList, chainId: number) => {
      try {
        const url =
          list.chainId === '0'
            ? getApiUrl(`/list/${list.providerKey}/${list.key}`)
            : getApiUrl(`/list/${list.providerKey}/${list.key}?chainId=${chainId}`)

        const response = await fetch(url)

        if (response.ok) {
          const data = await response.json()
          if (data?.tokens && Array.isArray(data.tokens)) {
            const tokens: Token[] = data.tokens.map((token: Token) => ({
              ...token,
              hasIcon: true,
              sourceList: `${list.providerKey}/${list.key}`,
              isBridgeToken: list.providerKey.includes('bridge'),
            }))

            const listKey = `${list.providerKey}/${list.key}`
            setListTokens(listKey, tokens)
            // updateCombinedTokenList will be triggered by the effect watching
            // tokensByList changes — but since setListTokens is batched we
            // call it manually here so incremental results appear immediately.
            // We need a micro-delay for the state to settle.
            setTimeout(updateCombinedTokenList, 0)
          }
        } else if (response.status === 404) {
          console.log(`List ${list.providerKey}/${list.key} not available for chain ${chainId}`)
          toggleList(`${list.providerKey}/${list.key}`, false)
        } else {
          console.error(
            `Failed to fetch list ${list.providerKey}/${list.key}: ${response.status} ${response.statusText}`,
          )
        }
      } catch (error) {
        console.error(`Network error fetching list ${list.name}:`, error)
      }
    },
    [setListTokens, toggleList, updateCombinedTokenList],
  )

  // ---------------------------------------------------------------------------
  // Fetch all token lists for a chain
  // ---------------------------------------------------------------------------

  const tryFetchTokenLists = useCallback(
    async (chainId: number) => {
      const lists = availableListsRef.current
      const relevantLists = lists.filter(
        (list) => list.chainId === chainId.toString() || list.chainId === '0',
      )

      // Clear previous tokens
      clearTokens()
      setAllTokens([])
      setFilteredTokens([])

      // Process lists in batches of 2
      const batchSize = 2
      for (let i = 0; i < relevantLists.length; i += batchSize) {
        const batch = relevantLists.slice(i, i + batchSize)
        await Promise.all(batch.map((list) => processListWithRetry(list, chainId)))
      }
    },
    [clearTokens, processListWithRetry],
  )

  // ---------------------------------------------------------------------------
  // Initialization effect
  // ---------------------------------------------------------------------------

  useEffect(() => {
    let cancelled = false

    const initialize = async () => {
      initializeApiBase()
      if (cancelled) return

      setIsInitialized(true)
      fetchMetrics()

      // Fetch available lists
      try {
        const response = await fetch(getApiUrl('/list'))
        if (cancelled || !response.ok) return

        const data = await response.json()
        if (cancelled) return

        const uniqueLists = new Map<string, AvailableList>()
        data.forEach((info: Record<string, unknown>) => {
          const key = `${info.providerKey}-${info.key}-${info.chainId}`
          if (!uniqueLists.has(key)) {
            uniqueLists.set(key, {
              key: info.key as string,
              name: (info.name as string) || (info.key as string),
              providerKey: info.providerKey as string,
              chainId: info.chainId?.toString() || '0',
              type: (info.type as string) || 'hosted',
              default: (info.default as boolean) || false,
            })
          }
        })
        setAvailableLists(Array.from(uniqueLists.values()))
      } catch (error) {
        console.error('Failed to fetch available lists:', error)
      }
    }

    initialize()

    return () => {
      cancelled = true
    }
  }, [])

  // ---------------------------------------------------------------------------
  // When selectedNetwork changes and we're in token mode, fetch token lists
  // ---------------------------------------------------------------------------

  useEffect(() => {
    if (selectedNetwork && urlType === 'token') {
      tryFetchTokenLists(selectedNetwork.chainId)
    }
  }, [selectedNetwork, urlType])

  // ---------------------------------------------------------------------------
  // Derived values
  // ---------------------------------------------------------------------------

  const list = useMemo(() => Array.from(tokensByList.entries()), [tokensByList])

  const underChain = useMemo(
    () =>
      list.filter(([, tokens]) => {
        const tokensForNetwork = tokens.filter((token) => token.chainId === selectedChain)
        return tokensForNetwork.length > 0
      }),
    [list, selectedChain],
  )

  const tokenCount = useMemo(
    () =>
      _(underChain)
        .flatMap(([, tkns]) => tkns)
        .uniqBy((v) => v.address.toLowerCase())
        .value().length,
    [underChain],
  )

  // ---------------------------------------------------------------------------
  // Handlers
  // ---------------------------------------------------------------------------

  const handleSelectNetwork = useCallback(
    (network: NetworkInfo) => {
      setSelectedChain(network.chainId)
      setSelectedNetwork(network)
      generateUrl({ chain: network.chainId })

      if (urlType === 'token') {
        tryFetchTokenLists(network.chainId)
      }
    },
    [generateUrl, urlType, tryFetchTokenLists],
  )

  const handleTokenListToggle = useCallback(
    (listKey: string, enabled: boolean) => {
      toggleList(listKey, enabled)
      setTimeout(updateCombinedTokenList, 0)
    },
    [toggleList, updateCombinedTokenList],
  )

  const handleTokenListToggleAll = useCallback(
    (enabled: boolean) => {
      toggleAll(enabled)
      setTimeout(updateCombinedTokenList, 0)
    },
    [toggleAll, updateCombinedTokenList],
  )

  const handleApiTypeSelect = useCallback(
    (type: ApiType) => {
      setUrlType(type)
      setGeneratedUrl('')
      setPreviewError(false)
      setTokenAddress('')
    },
    [],
  )

  const handleApiTypeLoadTokens = useCallback(() => {
    if (selectedNetwork) {
      tryFetchTokenLists(selectedNetwork.chainId)
    }
  }, [selectedNetwork, tryFetchTokenLists])

  const handleApiTypeGenerate = useCallback(() => {
    if (selectedNetwork) {
      generateUrl({ chain: selectedNetwork.chainId })
    }
  }, [selectedNetwork, generateUrl])

  const handleApiTypeReset = useCallback(() => {
    setGeneratedUrl('')
    setTokenAddress('')
    setPreviewError(false)
  }, [])

  const handleListSelect = useCallback(
    (selection: { key: string; providerKey: string }) => {
      setSelectedList(selection)
      const name = `${selection.providerKey}/${selection.key}`
      setListName(name)
      generateUrl({ list: name })
    },
    [generateUrl],
  )

  const handleSelectToken = useCallback(
    (token: Token) => {
      setTokenAddress(token.address)
      generateUrl({ address: token.address })
    },
    [generateUrl],
  )

  const handleTokenAddressBack = useCallback(() => {
    setTokenAddress('')
    setGeneratedUrl('')
    setPreviewError(false)
    setIconExists(true)
  }, [])

  const handleTokenAddressInput = useCallback(
    (address: string) => {
      setTokenAddress(address)
      generateUrl({ address })
    },
    [generateUrl],
  )

  const handleNetworkName = useCallback((fn: (id: string | number) => string) => {
    setGetNetworkNameFn(() => fn)
  }, [])

  const resetForm = useCallback(() => {
    if (urlType === 'token' && tokenAddress) {
      // Only reset the preview state, maintaining token selection
      previewRef.current?.resetPreview()
      generateUrl()
    } else {
      // Full reset
      setSelectedChain(null)
      setTokenAddress('')
      setGeneratedUrl('')
      setPreviewError(false)
      previewRef.current?.resetPreview()
    }
  }, [urlType, tokenAddress, generateUrl])

  // ---------------------------------------------------------------------------
  // Derived display helpers
  // ---------------------------------------------------------------------------

  const networkName = selectedNetwork ? getNetworkNameFn(selectedNetwork.chainId) : ''

  const showTokenBrowser = urlType === 'token'

  const selectedTokenName = useMemo(() => {
    if (filteredTokens.length === 0) return 'Unknown Token'
    return (
      filteredTokens.find((t) => t.address.toLowerCase() === tokenAddress.toLowerCase())?.name ||
      'Unknown Token'
    )
  }, [filteredTokens, tokenAddress])

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  if (!isInitialized) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="space-y-4 text-center">
          <div className="loading loading-spinner loading-lg"></div>
          <p>Initializing...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto max-w-3xl p-4 sm:p-8">
      <div className="space-y-4 text-center">
        <h1 className="h1">URL Wizard</h1>
        <p className="text-lg">Generate URLs for the Gib Assets API</p>
      </div>

      <div className="card space-y-6">
        {/* API Type Selection */}
        <ApiTypeSelector
          urlType={urlType}
          network={selectedNetwork}
          onSelect={handleApiTypeSelect}
          onLoadTokens={handleApiTypeLoadTokens}
          onGenerate={handleApiTypeGenerate}
          onReset={handleApiTypeReset}
        />

        {/* Token List Selection (only for list type) */}
        {urlType === 'list' && (
          <TokenListSelector
            availableLists={availableLists}
            selectedList={selectedList}
            onSelect={handleListSelect}
          />
        )}

        {/* Network Selection */}
        <NetworkSelect
          isOpenToStart={false}
          network={selectedNetwork}
          onSelect={handleSelectNetwork}
          onNetworkName={handleNetworkName}
        />

        {/* Token Browser (show when network is selected in token mode) */}
        {urlType === 'token' && selectedNetwork && !tokenAddress && (
          <TokenBrowser
            networkName={networkName}
            filteredTokens={filteredTokens}
            isCircularCrop={isCircularCrop}
            currentPage={currentPage}
            tokensPerPage={tokensPerPage}
            onPageChange={setCurrentPage}
            onPerPageUpdate={setTokensPerPage}
            onSelectToken={handleSelectToken}
          >
            <TokenSearch
              count={tokenCount}
              networkName={networkName}
              onSearchUpdate={setCurrentSearchState}
              selectedChain={selectedChain}
              enabledLists={enabledLists}
              tokensByList={tokensByList}
              onToggleList={handleTokenListToggle}
              onToggleAll={handleTokenListToggleAll}
            />
          </TokenBrowser>
        )}

        {/* Manual Token Input */}
        {urlType === 'token' && selectedNetwork && tokenAddress && (
          <TokenAddressInput
            address={tokenAddress}
            onBack={handleTokenAddressBack}
            onInput={handleTokenAddressInput}
          />
        )}

        {/* Generated URL Display */}
        {generatedUrl && (
          <>
            <UrlDisplay url={generatedUrl} />

            {/* Preview */}
            {urlType !== 'list' && previewError && (
              <ErrorMessage
                urlType={urlType as 'token' | 'network'}
                chainId={selectedNetwork?.chainId}
                networkName={getNetworkNameFn(selectedNetwork?.chainId || '')}
                tokenAddress={tokenAddress}
                generatedUrl={generatedUrl}
              />
            )}

            {urlType !== 'list' &&
              !previewError &&
              ((!showTokenBrowser && urlType === 'network') ||
                (urlType === 'token' && tokenAddress)) && (
                <div className="space-y-2">
                  <TokenPreview
                    ref={previewRef}
                    url={generatedUrl}
                    previewError={previewError}
                    iconExists={iconExists}
                    isCircularCrop={isCircularCrop}
                    backgroundColor={backgroundColor}
                    showColorPicker={showColorPicker}
                    setPreviewError={setPreviewError}
                    setIconExists={setIconExists}
                    setIsCircularCrop={setIsCircularCrop}
                    setBackgroundColor={setBackgroundColor}
                    setShowColorPicker={setShowColorPicker}
                  />
                  {filteredTokens.length > 0 && (
                    <div className="text-center text-sm text-surface-600 dark:text-surface-300">
                      {selectedTokenName}
                    </div>
                  )}
                </div>
              )}

            {/* Reset Button */}
            <button
              className="variant-ghost-surface btn w-full"
              type="button"
              onClick={resetForm}
            >
              <i className="fas fa-redo mr-2"></i>
              Reset
            </button>
          </>
        )}
      </div>

      {/* API Documentation Link */}
      <div className="text-center">
        <a href="#/docs" className="variant-ghost-surface btn">
          <i className="fas fa-book mr-2"></i>
          View Full API Documentation
        </a>
      </div>
    </div>
  )
}
